dist: trusty
sudo: false
language: c

matrix:
  include:

    # default linux build with gcc
    - os: linux
      env:
        - TEST="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
          - gcc-6
      script:
        - ./configure
        - make
        - make runtest

    # linux build with openssl and gcc
    - os: linux
      env:
        - TEST="linux gcc (openssl)"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      script:
        - ./configure --enable-openssl
        - make
        - make runtest

    # linux build with openssl and clang
    - os: linux
      env:
        - TEST="linux clang (openssl)"
      addons:
        apt:
          packages:
            - clang
      script:
        - CC=clang ./configure --enable-openssl
        - make
        - make runtest

    # default osx build with xcode (clang)
    - os: osx
      env:
        - TEST="osx XCode 8.2"
      osx_image: xcode8.2
      script:
        - ./configure
        - make
        - make runtest

    # code format check
    - os: linux
      env:
        - TEST="clang-format"
      addons:
        apt:
          packages:
            - clang-format-3.9
      script:
        - ./format.sh -d

    # valgrind
    - os: linux
      env:
        - TEST="valgrind (openssl)"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - valgrind
      script:
        - ./configure --enable-openssl
        - make
        - make runtest-valgrind

    # big-endian
    - os: linux
      sudo: true
      env:
        - TEST="big-endian"
      addons:
        apt:
          packages:
            - qemu-user-static
      before_install:
        - sudo apt-get install emdebian-archive-keyring debian-archive-keyring
        - echo 'deb http://www.emdebian.org/debian squeeze main' | sudo tee /etc/apt/sources.list.d/emdebian.list > /dev/null
        - echo 'deb http://ftp.us.debian.org/debian squeeze main' | sudo tee -a /etc/apt/sources.list.d/emdebian.list > /dev/null
        - sudo apt-get update
        - sudo apt-get install linux-libc-dev-mips-cross libc6-mips-cross libc6-dev-mips-cross binutils-mips-linux-gnu gcc-4.4-mips-linux-gnu cpp-4.4-mips-linux-gnu libgomp1-mips-cross gcc-4.8-base-mips-cross -y
      script:
        - mips-linux-gnu-gcc -dumpmachine
        - export CC=mips-linux-gnu-gcc
        - ./configure
        - make
        - file test/srtp_driver
