dist: trusty
sudo: false
language: c
cache: ccache
osx_image: xcode8.2


matrix:
  include:
    - os: linux
      env:
        - TEST="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      script:
        - ./configure
        - make
        - make runtest
    - os: linux
      env:
        - TEST="linux clang"
      compiler:
        - clang
      script:
        - ./configure
        - make
        - make runtest
