dist: trusty
sudo: false
language: c

matrix:
  include:

    # default linux build with gcc
    - os: linux
      env:
        - TEST="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
          - gcc-6
      script:
        - ./configure
        - make
        - make runtest

    # linux build with openssl and gcc
    - os: linux
      env:
        - TEST="linux gcc (openssl)"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      script:
        - ./configure --enable-openssl
        - make
        - make runtest

    # linux build with openssl and clang
    - os: linux
      env:
        - TEST="linux clang (openssl)"
      addons:
        apt:
          packages:
            - clang
      script:
        - CC=clang ./configure --enable-openssl
        - make
        - make runtest

    # default osx build with xcode (clang)
    - os: osx
      env:
        - TEST="osx XCode 8.2"
      osx_image: xcode8.2
      script:
        - ./configure
        - make
        - make runtest

    # code format check
    - os: linux
      env:
        - TEST="clang-format"
      addons:
        apt:
          packages:
            - clang-format-3.9
      script:
        - ./format.sh -d

    # valgrind
    - os: linux
      env:
        - TEST="valgrind (openssl)"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - valgrind
      script:
        - ./configure --enable-openssl
        - make
        - make runtest-valgrind

    # big-endian
    - os: linux
      env:
        - TEST="big-endian"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      script:
        - ./configure
        - make
        - file test/srtp_driver
