dist: trusty
sudo: false
language: c

matrix:
  include:
    - os: linux
      env:
        - TEST="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      script:
        - ./configure
        - make
        - make runtest
    - os: linux
      env:
        - TEST="linux clang"
        - CC=clang
      addons:
        apt:
          packages:
            - clang
      script:
        - ./configure
        - make
        - make runtest
