dist: trusty
sudo: false
language: c

matrix:
  include:
    - os: linux
      env:
        - TEST="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      script:
        - ./configure
        - make
        - make runtest
    - os: linux
      env:
        - TEST="linux clang"
      addons:
        apt:
          packages:
            - clang
      script:
        - CC=clang ./configure
        - make
        - make runtest
    - os: linux
      env:
        - TEST="clang-format"
      addons:
        apt:
          packages:
            - clang-format
      script:
        - ./format -d
