sudo: false
language: c
osx_image: xcode8.2
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
script:
  - ./configure && make && make runtest
  - make clean
  - ./configure --enable-openssl && make && make runtest
