sudo: false
language: c
osx_image: xcode8.2
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
# OSX
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update;
      brew install --force openssl && brew link --force openssl;
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
    fi
script:
  - ./configure && make && make runtest
  - make clean
  - openssl version -a
  - ./configure --enable-openssl && make && make runtest
