sudo: false
language: c
osx_image: xcode8.2
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
# OSX
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update;
      brew install openssl && brew link --force openssl;
    fi
script:
  - ./configure && make && make runtest
  - make clean
  - openssl version -a
  - ./configure --enable-openssl && make && make runtest
