name: AutoTools CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crypto: [internal, openssl, nss, mbedtls]
        include:
          - crypto: internal
            configure-crypto-enable: ""
          - crypto: openssl
            configure-crypto-enable: "--enable-openss"
          - crypto: nss
            configure-crypto-enable: "--enable-nss"
          - crypto: mbedtls
            configure-crypto-enable: "--enable-mbedtls"

    runs-on: ${{ matrix.os }}
    
    env:
      CTEST_OUTPUT_ON_FAILURE: 1

    steps:
    - name: Setup Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install valgrind

    - name: Setup Ubuntu NSS
      if: matrix.os == 'ubuntu-latest' && matrix.crypto == 'nss'
      run: sudo apt-get install libnss3-dev
      
    - name: Setup Ubuntu MbedTLS
      if:  matrix.os == 'ubuntu-latest' && matrix.crypto == 'mbedtls'
      run: sudo apt-get install libmbedtls-dev
    
    - name: Setup macOS OpenSSL
      if: matrix.os == 'macos-latest' && matrix.crypto == 'openssl'
      run: echo "configure-crypto-dir=--with-openssl-dir=$(brew --prefix openssl@1.1)" >> $GITHUB_ENV
      
    - name: Setup macOS NSS
      if:  matrix.os == 'macos-latest' && matrix.crypto == 'nss'
      run: brew install nss
      
    - name: Setup macOS MbedTLS
      if:  matrix.os == 'macos-latest' && matrix.crypto == 'mbedtls'
      run: brew install mbedtls
      
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure
      run: EXTRA_CFLAGS=-Werror ./configure ${{ matrix.configure-crypto-enable}} ${{env.configure-crypto-dir}}

    - name: Build
      run: make

    - name: Test
      run: make runtest
      
    - name: Test Valgrind
      if:  matrix.os == 'ubuntu-latest'
      run: make runtest-valgrind
