name: Code Formatting Check

on:
  push:
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Clang Format
        run: sudo apt install clang-format-3.9
      - name: Run clang format
        run: CLANG_FORMAT=clang-format-3.9 ./format.sh -d
